### ISSUE TITLE
Unwanted delay in Automations

### ISSUE THREAD

**Issue by f00dagi** [klali/ha-plejd#21]
Hi!

update: for troubleshooting purposes I also made a clean install of latest hassio image and latest build of ha-plejd on different hardware (rpi4) and a new memory card. Same Plejd setup in my house. On top of that I installed only samba and ssh and created a light group to minimize the risk of interference from other plugins/code. Unfortunately the same behavior with only one of several lamps in that group turns on. If turning on lamps one by one it works just fine.

Thanks for a great development project, very useful for us Plejd users.

I want to turn on multiple lights at the same time but with Plejd-Hassio I have been rather unsuccessful. 

For example when I run an automation what happens is that the automation turn on the first light immediately but there is an (exact?) delay of 10 seconds between each following light turning on. 

If I trigger two lights manually they both turn on immediately.

I have also tried the plugin group lights and starting several entities under one button but that results in only the first light turning on.

I can not be sure but to me it seems like your Plejd-Hassio integration has some kind of flaw?

Thanks again for your work!

**Comment by klali** [comment]
Do you get anything in your logs?

Can you turn on debugging for the plejd component and report back?

**Comment by f00dagi** [comment]
Thanks for your reply.

update: to improve readability of code
turn_on_lights_by_automation: http://bit.ly/2NqWq1S
turn_on_lights_by_light group: http://bit.ly/2K1DAMO

Thanks for your time. I am really eager to get this working properly. If you want more debugging data just let me know.

**Comment by klali** [comment]
Very interesting. This is probably the same/related to #10 

So the 10 seconds seem to be the SERVICE_CALL_LIMIT from core.py where it has a timeout of 10 seconds on all service calls. The actual call doesn't take this amount of time, but maybe we're not returning correctly or marking that we're done correctly.

I'll try to poke a bit at this and see if I can reproduce and if so fix it.

If you want to debug this a bit on your own, you can add debug logs on exit of the turn_on() and turn_off() functions and see what the time is when those are called.

**Comment by f00dagi** [comment]
Interesting, then there is a lead to the root cause, sounds promising.

I tried to google on how to add debug logs as you request but I cannot find any examples. Could you point me in the right direction or modify my code below to include debugging. Thanks.
```
- id: '1570825239747'
  alias: Time
  trigger:
  - at: '14:08'
    platform: time
  condition: []
  action:
  - data:
      brightness: '1'
      entity_id: light.allrum_tak
    service: light.turn_on
  - data:
      brightness: '1'
      entity_id: light.allrum_vagg
    service: light.turn_on
  - data:
      brightness: '1'
      entity_id: light.trappa_vagg
    service: light.turn_on
```
